# Generated by Django 5.2.15 on 2026-07-01 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('pages', 'Páginas'), ('books', 'Livros'), ('minutes', 'Minutos')], max_length=10)),
                ('period', models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], max_length=10)),
                ('target_value', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='library.userbook')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('target_value__gt', 0)), name='ck_goal_target_pos'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('user_book__isnull', True)), fields=('user', 'metric', 'period'), name='uq_goal_global_active'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('user_book__isnull', False)), fields=('user_book', 'metric', 'period'), name='uq_goal_book_active')],
            },
        ),
    ]
