# Generated by Django 5.2.15 on 2026-07-01 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('book_started', 'Livro iniciado'), ('book_finished', 'Livro concluído'), ('level_up', 'Subiu de nível'), ('achievement_unlocked', 'Conquista desbloqueada'), ('streak_kept', 'Ofensiva mantida'), ('quest_completed', 'Quest concluída'), ('daily_summary', 'Resumo do dia')], max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('event_date', models.DateField()),
                ('visibility', models.CharField(choices=[('private', 'Privado'), ('followers', 'Seguidores'), ('public', 'Público')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='ix_timeline_user_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('type', 'daily_summary')), fields=('user', 'event_date'), name='uq_timeline_daily_summary')],
            },
        ),
    ]
