# Generated by Django 5.2.15 on 2026-07-01 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('criteria_type', models.CharField(max_length=40)),
                ('criteria_value', models.PositiveIntegerField()),
                ('is_repeatable', models.BooleanField(default=False)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('community_id', models.UUIDField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('criteria_value__gt', 0)), name='ck_quest_criteria_pos')],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('criteria_type', models.CharField(max_length=40)),
                ('criteria_value', models.PositiveIntegerField(blank=True, null=True)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('source_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='quests.quest')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='quests.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('expired', 'Expirada')], default='in_progress', max_length=12)),
                ('progress_value', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quests', to='quests.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.CheckConstraint(condition=models.Q(('xp_reward__gte', 0)), name='ck_achievement_xp_reward_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='uq_userachievement'),
        ),
        migrations.AddIndex(
            model_name='userquest',
            index=models.Index(fields=['user', 'status'], name='ix_userquest_user_status'),
        ),
        migrations.AddConstraint(
            model_name='userquest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'quest'), name='uq_userquest_active'),
        ),
    ]
