# Generated by Django 5.2.15 on 2026-07-02 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userquest',
            constraint=models.CheckConstraint(condition=models.Q(('progress_value__gte', 0)), name='ck_userquest_progress_nonneg'),
        ),
    ]
