# Generated by Django 5.2.15 on 2026-07-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_userquest_ck_userquest_progress_nonneg'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='quest',
            constraint=models.CheckConstraint(condition=models.Q(('xp_reward__gte', 0)), name='ck_quest_xp_reward_nonneg'),
        ),
    ]
