# Generated by Django 5.2.15 on 2026-07-01 14:24

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('normalized_name'), name='uq_author_norm')],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(max_length=120)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('normalized_name'), name='uq_genre_norm')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('source', models.CharField(choices=[('google_books', 'Google Books'), ('open_library', 'Open Library'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('total_pages', models.PositiveIntegerField()),
                ('cover_url', models.URLField(blank=True)),
                ('published_year', models.SmallIntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author')),
                ('genres', models.ManyToManyField(related_name='books', to='catalog.genre')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('total_pages__gt', 0)), name='ck_book_pages_pos')],
            },
        ),
    ]
