# Generated by Django 5.2.15 on 2026-07-01 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('xp_required', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('longest_count', models.PositiveIntegerField(default=0)),
                ('last_active_on', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('longest_count__gte', models.F('current_count'))), name='ck_streak_longest')],
            },
        ),
        migrations.CreateModel(
            name='StreakFreeze',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_on', models.DateField()),
                ('period_key', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_freezes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'period_key'), name='uq_freeze_user_period')],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('pages_read', 'Páginas lidas'), ('book_completed', 'Livro concluído'), ('review_written', 'Resenha escrita'), ('goal_met', 'Meta cumprida'), ('quest_completed', 'Quest concluída'), ('achievement_unlocked', 'Conquista desbloqueada'), ('correction', 'Correção')], max_length=24)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='ix_xp_user_created')],
            },
        ),
    ]
